install_all:
	go install github.com/cmu440/tribbler/libstore
	go install github.com/cmu440/tribbler/storageserver
	go install github.com/cmu440/tribbler/tribclient
	go install github.com/cmu440/tribbler/tribserver
	go install github.com/cmu440/tribbler/runners/srunner
	go install github.com/cmu440/tribbler/runners/lrunner
	go install github.com/cmu440/tribbler/runners/trunner
	go install github.com/cmu440/tribbler/runners/crunner
